Add tox, prove that python 3.12 is supported
nimasmi/django-gov-notify pull request #11
Opened 2024-04-17 11:54 UTC by duncanjbrown

Our project depends on Python 3.12 but this package doesn't officially support it.

This PR proves that it does by adding `tox` (https://tox.wiki/en/4.14.2/) to test different python versions, then relaxing the python version constraint to allow 3.12.

2024-04-17 13:24 UTC, duncanjbrown commented
I see there's more work to do to get the various django/python combinations in CI building and passing — working on that

2024-04-17 13:49 UTC, nimasmi requested changes
Thanks for this @duncanjbrown!

I have had trouble getting this to build locally for me, but I think a move to tox is a good thing in the light of supporting multiple Python versions.

2024-04-17 13:51 UTC, nimasmi commented
Ah, I see that you have modified things since I drafted my comments earlier. I had also forgotten that the Gitlab CI config permits testing against multiple Python versions. I'm happier working with tooling I'm more familiar with, which is an argument against tox, but on the other hand, tox does streamline the local running of multiple environment tests.

2024-04-18 09:06 UTC, duncanjbrown commented
Thanks and sorry for the flapping 😅 ! Implemented tox (which was interesting anyway) and then realised more was going on in CI. I've still got the tox branch — can dust off after this for reconsideration.

2024-04-18 13:52 UTC, nimasmi commented on .github/workflows/CI-tests.yml
> +            python-version: "3.10"
**Praise**: Thanks for this annotation, it'll make updating easier in future.

2024-04-22 22:19 UTC, duncanjbrown commented
Thanks! I've made a few changes so the build actually passes 😅 — please merge if you're (still) happy

2024-04-22 22:19 UTC, duncanjbrown commented
Passing build: https://github.com/i-dot-ai/django-gov-notify/actions/runs/8791575912

2024-04-24 10:18 UTC, nimasmi commented
Thanks again @duncanjbrown. I prefer to keep the lint, build, and test CI steps separate, though I see that it now completes much faster, which is a time and CO₂ emissions improvement at least.

The improvements to the test matrix, and interdependencies are great, though.

2024-04-24 17:01 UTC, duncanjbrown commented
No problem — separated and updated

2024-05-02 13:54 UTC, merged

2024-05-02 13:59 UTC, nimasmi commented
Thanks very much for your contributions @duncanjbrown.

I have merged this via #12, and published version 0.5.0 on PyPI: https://pypi.org/project/django-gov-notify/.